### ISSUE TITLE
[en_US] Translator access request

### ISSUE THREAD

**Issue by Xaroth** [TrueBrain/OpenTTD-team-test#14]
Hi,

I would like to ask for access to help translating OpenTTD and its subprojects into **English (US)**.

The **English (US)** language is well known to me, and I promise to cooperate with my fellow translators to give the end-users the best experience possible.

Thank you,

**Comment by DorpsGek** [comment]
Thank you @Xaroth for your request to be part of our community.

Soon, often not longer than a day, a Core Developer will process your request.
Till that time, please sit tight.

---

_For the Core Developers_

User @Xaroth is requesting access to language __en_US__.

Please reply with either `/approve` or `/deny` in the first line of your comment to process this request.
If you `/deny`, please be so kind to leave a reason why.

**Comment by DorpsGek** [comment]
Good news, @Xaroth, your request has been approved!
You now have access to en_US.

You can login to [eints](https://translator.openttd.org/language/en_US) to start working on the translation.
Feel free to talk to your fellow translators in your [Team](https://github.com/orgs/OpenTTD/teams/en_US).
